[theme]
primaryColor = "#41A84F"          # Brand color for buttons/sliders
backgroundColor = "#F7F7F1"       # Main background
secondaryBackgroundColor = "#262730" # Sidebar and widget background
textColor = "#1C2627"             # Main text
font = "sans serif"

[server]
headless = true
enableCORS = false
